### Get Customers Valid Auth (username = 'rish' converted to Base64
GET http://localhost:4004/odata/v4/banking/Customers
Authorization: Basic cmlzaDoxMjM0
Accept: application/json

### Get Customers invalid Auth
GET http://localhost:4004/odata/v4/banking/Customers
Authorization: Basic cmlzaDawdawd
Accept: application/json

### Get Accounts(No Authorization) Only authenticated user needed
GET http://localhost:4004/odata/v4/banking/Accounts
Authorization: Basic cawdawdawd
Accept: application/json

### Get Transactions
GET http://localhost:4004/odata/v4/banking/Transactions
Authorization: Basic cawdawdawd
Accept: application/json

### Get Balance Function
GET http://localhost:4004/odata/v4/banking/getBalance(accountId='1')
Authorization: Basic cmlzaDoxM
Accept: application/json

### Get Customer Accounts
GET http://localhost:4004/odata/v4/banking/getCustomerAccounts(customerId='1')
Authorization: Basic cmlzaDoxM
Accept: application/json

### Action deposit
POST http://localhost:4004/odata/v4/banking/deposit
Authorization: Basic cmlzaDoxMjM0
Content-Type: application/json
Accept: application/json

{
    "accountId": "1",
    "amount": 2000
}

### Withdraw Deposit
POST http://localhost:4004/odata/v4/banking/withdraw
Authorization: Basic cmlzaDoxMjM0
Content-Type: application/json
Accept: application/json

{
    "accountId": "1",
    "amount": 10000
}

###
curl -X POST \
  "https://3ab10685trial.authentication.us10.hana.ondemand.com/oauth/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "sb-banking_capm-3ab10685trial-dev!t620376:c7d7e955-5708-4d6e-a66a-fe50fdaea0f3$Oq7YAhNxLtohdwV2LfT8zW9uS1C4MrRmKaRuyFIixEs=" \
  -d "grant_type=client_credentials"
